### PR TITLE
Add new websocket messages for GW 3.7-rc7

### PR DESCRIPTION
**Pull request by zweckj**

### CODE REVIEW

**Comment by Marcocanc** [comment]
Assuming this will improve reliability in detecting brew active state after the 3.7-rc7 update? 😊

**Comment by zweckj** [comment]
> Assuming this will improve reliability in detecting brew active state after the 3.7-rc7 update? 😊

exactly 😉

**Comment by Marcocanc** [comment]
@zweckj FYI, I'm still having very unreliable brew status updates on my Linea Micra with the latest HASS Core release. Is this supposed to be fixed in that version?

**Comment by zweckj** [comment]
@Marcocanc yes, should be fixed in 2025.1. I don’t have any problems with my Micra. You could enable the debug logs for the integration, that should give you all the websocket messages the machine sends.

**Comment by Marcocanc** [comment]
Thanks for the quick response. I'll do that and test this week. Will let you know if I find anything of value.

**Pull request merged**
